## Q1. Basic operations on a 1-D NumPy array

In [2]:
import numpy as np

arr = np.array([100, 29, 80, 40, 50])

print("Original array:", arr)


print("After adding 2:", arr + 2)


print("After multiplying by 3:", arr * 3)


print("After dividing by 2:", arr / 2)

Original array: [100  29  80  40  50]
After adding 2: [102  31  82  42  52]
After multiplying by 3: [300  87 240 120 150]
After dividing by 2: [50.  14.5 40.  20.  25. ]


## Q2. Basic NumPy array operations

### Q2(a). Reverse the given NumPy array

In [3]:
arr = np.array([10, 20, 30, 6, 4, 5])

print("Original array:", arr)
print("Reversed array:", arr[::-1])

Original array: [10 20 30  6  4  5]
Reversed array: [ 5  4  6 30 20 10]


### Q2(b). Find the most frequent value and its indices

In [4]:

x = np.array([10, 29, 366, 48, 50, 14, 29, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent_x = values[np.argmax(counts)]
indices_x = np.where(x == most_frequent_x)[0]

print("Array x:", x)
print("Most frequent value:", most_frequent_x)
print("Frequency:", np.max(counts))
print("Indices:", indices_x)


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent_y = values[np.argmax(counts)]
indices_y = np.where(y == most_frequent_y)[0]

print("\nArray y:", y)
print("Most frequent value:", most_frequent_y)
print("Frequency:", np.max(counts))
print("Indices:", indices_y)

Array x: [ 10  29 366  48  50  14  29   1   1   1]
Most frequent value: 1
Frequency: 3
Indices: [7 8 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Frequency: 3
Indices: [0 1 2]


## Q3. Access elements using row and column indices

In [5]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2-D array:")
print(arr)

print("1st row, 2nd column:", arr[0, 1])

print("3rd row, 1st column:", arr[2, 0])

2-D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


## Q4. `linspace()`, array properties, reshape and transpose

In [6]:

Hittin = np.linspace(10, 100, 25)

print("Array:")
print(Hittin)

print("\nDimensions:", Hittin.ndim)
print("Shape:", Hittin.shape)
print("Total elements:", Hittin.size)
print("Data type:", Hittin.dtype)
print("Total bytes consumed:", Hittin.nbytes)


transpose_reshape = Hittin.reshape(1, 25)
print("\nTranspose using reshape():")
print(transpose_reshape)


transpose_T = Hittin.T
print("\nUsing T attribute:")
print(transpose_T)

print("\nNote: For a 1-D NumPy array, T does not change its shape.")
print("To get a 25 x 1 transpose-like column array, use Hittin.reshape(25, 1).")

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transpose using reshape():
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]

Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Note: For a 1-D NumPy array, T does not change its shape.
To get a 25 x 1 transpose-like column array, use Hittin.reshape(25, 1).


## Q5. 2-D array statistics, reshape and resize

In [8]:
ucs420_Hittin = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original array:")
print(ucs420_Hittin)


print("\nMean:", np.mean(ucs420_Hittin))
print("Median:", np.median(ucs420_Hittin))
print("Maximum:", np.max(ucs420_Hittin))
print("Minimum:", np.min(ucs420_Hittin))
print("Unique elements:", np.unique(ucs420_Hittin))


reshaped_ucs420_Hittin = ucs420_Hittin.reshape(4, 3)

print("\nReshaped array (4 x 3):")
print(reshaped_ucs420_Hittin)


resized_ucs420_Hittin = np.resize(ucs420_Hittin, (2, 3))

print("\nResized array (2 x 3):")
print(resized_ucs420_Hittin)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 x 3):
[[10 20 30]
 [40 50 60]]
