# UCS420: Cognitive Computing — Assignment 6
## Question-wise NumPy-II Solutions

Each question is solved separately with code and explanatory output.

## Q1. Sensor Readings


In [1]:
import numpy as np

temperature = np.array([20, 88, 31, 35, 78, 27, 33, 40])

# (a) Add +2°C using vectorization
corrected_temperature = temperature + 2
print("(a) Corrected temperatures:", corrected_temperature)

# (b) Convert Celsius to Fahrenheit
fahrenheit = (9/5) * corrected_temperature + 32
print("(b) Fahrenheit temperatures:", fahrenheit)

# (c) Readings greater than 32°C
greater_than_32 = corrected_temperature[corrected_temperature > 32]
print("(c) Readings greater than 32°C:", greater_than_32)

# (d) Count readings exceeding 32°C
count_exceeding_32 = np.sum(corrected_temperature > 32)
print("(d) Number of readings exceeding 32°C:", count_exceeding_32)

# (e) Explanation
print("\n(e) Vectorization applies an operation to the whole NumPy array at once,")
print("while Boolean indexing selects values using a condition. Both avoid explicit")
print("Python loops and are generally faster and more concise for array processing.")

(a) Corrected temperatures: [22 90 33 37 80 29 35 42]
(b) Fahrenheit temperatures: [ 71.6 194.   91.4  98.6 176.   84.2  95.  107.6]
(c) Readings greater than 32°C: [90 33 37 80 35 42]
(d) Number of readings exceeding 32°C: 6

(e) Vectorization applies an operation to the whole NumPy array at once,
while Boolean indexing selects values using a condition. Both avoid explicit
Python loops and are generally faster and more concise for array processing.


## Q2. Daily Steps

In [2]:
steps = np.array([
    [9000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# (a) Total steps
print("(a) Total steps:", np.sum(steps))

# (b) Mean number of steps
print("(b) Mean steps:", np.mean(steps))

# (c) Maximum and minimum
print("(c) Maximum:", np.max(steps))
print("    Minimum:", np.min(steps))

# (d) Total steps for each day (axis=0)
print("(d) Total steps for each day:", np.sum(steps, axis=0))

# (e) Total steps for each user (axis=1)
print("(e) Total steps for each user:", np.sum(steps, axis=1))

# (f) Position of maximum using argmax()
max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("(f) Maximum value position (user index, day index):", max_position)
print("    Maximum steps:", steps[max_position])

(a) Total steps: 88200
(b) Mean steps: 7350.0
(c) Maximum: 9500
    Minimum: 4500
(d) Total steps for each day: [30500 27300 30400]
(e) Total steps for each user: [22300 24500 14400 27000]
(f) Maximum value position (user index, day index): (np.int64(3), np.int64(2))
    Maximum steps: 9500


## Q3. NumPy Arrays, Slicing, Copying, Flattening and Raveling

In [3]:
# (a) Original array
original = np.array([1, 2, 3, 4, 5, 6])
print("(a) original:", original)

# (b) Slice from index 1 to 4
subset = original[1:5]
print("(b) subset:", subset)

# (c) Modify subset
subset[0] = 999
print("(c) original after modifying subset:", original)
print("    subset:", subset)
print("    A normal NumPy slice is a view, so the original is affected.")

# (d) Slice using copy()
copied = original[1:5].copy()
copied[0] = 500
print("(d) original after modifying copied array:", original)
print("    copied:", copied)
print("    A copied array is independent of the original.")

# (e) Create 1 to 12 and reshape to 3x4
matrix = np.arange(1, 13).reshape(3, 4)
print("(e) 3 x 4 matrix:\n", matrix)

# (f) Indexing and slicing
print("(f) First row:", matrix[0, :])
print("    Last row:", matrix[-1, :])
print("    Second column:", matrix[:, 1])
print("    Rows 1-2 and columns 2-3:", matrix[1:3, 2:4])

# (g) flatten() and ravel()
flattened = matrix.flatten()
raveled = matrix.ravel()
print("(g) flatten():", flattened)
print("    ravel():", raveled)

# (h) Modify ravel result
raveled[0] = 1000
print("(h) Matrix after modifying ravel():\n", matrix)
print("    ravel():", raveled)

# (i) Modify flatten result
flattened[1] = 2000
print("(i) Matrix after modifying flatten():\n", matrix)
print("    flatten():", flattened)
print("    flatten() returns a copy, so the original is not affected.")

# (j) Array properties
print("(j) shape:", matrix.shape)
print("    ndim:", matrix.ndim)
print("    size:", matrix.size)
print("    dtype:", matrix.dtype)

(a) original: [1 2 3 4 5 6]
(b) subset: [2 3 4 5]
(c) original after modifying subset: [  1 999   3   4   5   6]
    subset: [999   3   4   5]
    A normal NumPy slice is a view, so the original is affected.
(d) original after modifying copied array: [  1 999   3   4   5   6]
    copied: [500   3   4   5]
    A copied array is independent of the original.
(e) 3 x 4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(f) First row: [1 2 3 4]
    Last row: [ 9 10 11 12]
    Second column: [ 2  6 10]
    Rows 1-2 and columns 2-3: [[ 7  8]
 [11 12]]
(g) flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
    ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
(h) Matrix after modifying ravel():
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
    ravel(): [1000    2    3    4    5    6    7    8    9   10   11   12]
(i) Matrix after modifying flatten():
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
    flatten(): [   1 2000    3    4    5    6    7

## Q4. Cognitive-Assistive System and Ordinary Least Squares

In [4]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# (a) Shape and dimensions
print("(a) Shape of X:", X.shape)
print("    Dimensions (ndim):", X.ndim)

# (b) Transpose
XT = X.T
print("\n(b) X.T:\n", XT)
print("    The transpose changes the 4x3 matrix into a 3x4 matrix.")
print("    Rows become columns, so each feature is represented as a row.")

# (c) X.T @ X
XTX = XT @ X
print("\n(c) X.T @ X:\n", XTX)

# (d) Inverse
XTX_inv = np.linalg.inv(XTX)
print("\n(d) Inverse of X.T @ X:\n", XTX_inv)

# (e) OLS: beta = (X.T X)^(-1) X.T y
beta = XTX_inv @ XT @ y
print("\n(e) OLS coefficients beta:", beta)

# (f) Interpretation
print("\n(f) Coefficient interpretation:")
print("    beta[0] = effect associated with one additional hour of sleep,")
print("              holding the other features constant.")
print("    beta[1] = effect associated with one additional unit of activity level,")
print("              holding the other features constant.")
print("    beta[2] = effect associated with one additional unit of stress level,")
print("              holding the other features constant.")
print("    Since the model has no intercept column, these coefficients describe")
print("    the fitted linear relationship through the origin.")

# (g) Predict for new user
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("\n(g) New user:", new_user)
print("    Predicted assistance score:", predicted_score)

(a) Shape of X: (4, 3)
    Dimensions (ndim): 2

(b) X.T:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
    The transpose changes the 4x3 matrix into a 3x4 matrix.
    Rows become columns, so each feature is represented as a row.

(c) X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

(d) Inverse of X.T @ X:
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

(e) OLS coefficients beta: [-0.15921454  0.14083853 10.06302242]

(f) Coefficient interpretation:
    beta[0] = effect associated with one additional hour of sleep,
              holding the other features constant.
    beta[1] = effect associated with one additional unit of activity level,
              holding the other features constant.
    beta[2] = effect associated with one additional unit of stress level,
              holding the other features constant.
    Since the model has no intercept column, these coefficients describe
    